name: Build xmrig-proxy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y git tar build-essential cmake libssl-dev uuid-dev

      - name: Clone and build static libuv
        run: |
          git clone https://github.com/libuv/libuv.git
          cd libuv
          sh autogen.sh
          ./configure --enable-static --disable-shared
          make -j$(nproc)
          sudo make install

      - name: Download and build static OpenSSL
        run: |
          git clone https://github.com/openssl/openssl.git
          cd openssl
          ./config no-shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
          make -j$(nproc)
          sudo make install

      - name: Clone xmrig-proxy repository
        run: |
          git clone https://github.com/C3Pool/xmrig-proxy.git

      - name: Build xmrig-proxy with static linking
        run: |
          mkdir xmrig-proxy/build
          cd xmrig-proxy/build
          cmake .. \
            -DCMAKE_EXE_LINKER_FLAGS="-static-libstdc++ -static-libgcc" \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_PREFIX_PATH=/usr/local/ssl
          make -j$(nproc)

      - name: Archive xmrig-proxy binary
        run: |
          tar -czvf xmrig-proxy.tar.gz xmrig-proxy/build/xmrig-proxy

      - name: Upload xmrig-proxy binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: xmrig-proxy
          path: xmrig-proxy.tar.gz
