name: Build XMRig

on: workflow_dispatch

jobs:
  build-windows:
    name: Build XMRig for Windows
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone XMRig dependencies
        run: |
          git clone https://github.com/xmrig/xmrig-deps.git c:/xmrig-deps
          cd c:/xmrig-deps
          git submodule update --init --recursive

      - name: Clone XMRig
        run: |
          git clone https://github.com/xmrig/xmrig.git
          cd xmrig
          git submodule update --init --recursive

      - name: Modify donate.h
        run: |
          cd xmrig/src
          sed -i 's/constexpr const int kDefaultDonateLevel = 1;/constexpr const int kDefaultDonateLevel = 0;/g' donate.h
          sed -i 's/constexpr const int kMinimumDonateLevel = 1;/constexpr const int kMinimumDonateLevel = 0;/g' donate.h

      - name: Build XMRig for Windows with static libraries
        run: |
          cd xmrig
          mkdir build && cd build
          cmake  .. -G "Unix Makefiles" -DXMRIG_DEPS=c:/xmrig-deps/gcc/x64
          make -j4

      - name: Archive Windows build
        run: |
          cd xmrig/build
          cp ../src/config.json .
          cp ../bin/WinRing0/WinRing0x64.sys .
          cp ../scripts/*.cmd .
          7z a -tzip -mx xmrig-windows.zip xmrig.exe config.json WinRing0x64.sys *.cmd
        shell: bash

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: XMRig-Windows
          path: xmrig/build/xmrig-windows.zip

  build-linux:
    name: Build XMRig for Linux
    runs-on: ubuntu-latest  # 使用最新的Ubuntu环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake automake libtool autoconf libhwloc-dev libuv1-dev

      - name: Clone XMRig
        run: |
          git clone https://github.com/xmrig/xmrig.git
          cd xmrig
          git submodule update --init --recursive
          mkdir -p build  # 确保build目录存在

      - name: Modify donate.h
        run: |
          cd xmrig/src
          sed -i 's/constexpr const int kDefaultDonateLevel = 1;/constexpr const int kDefaultDonateLevel = 0;/g' donate.h
          sed -i 's/constexpr const int kMinimumDonateLevel = 1;/constexpr const int kMinimumDonateLevel = 0;/g' donate.h

      - name: Build dependencies
        run: |
          cd xmrig/scripts
          ./build_deps.sh

      - name: Build XMRig for Linux with static libraries
        run: |
          cd xmrig/build
          cmake .. -DXMRIG_DEPS=../../scripts/deps -D CMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Archive Linux build
        run: |
          cd xmrig/build
          cp ../src/config.json .
          cp ../scripts/enable_1gb_pages.sh .
          cp ../scripts/randomx_boost.sh .
          7z a -tzip -mx xmrig-linux.zip xmrig config.json enable_1gb_pages.sh randomx_boost.sh
        shell: bash

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: XMRig-Linux
          path: xmrig/build/xmrig-linux.zip
